/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "livvnyazvxywfrmtblcy"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpdnZueWF6dnh5d2ZybXRibGN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYzMTA2ODIsImV4cCI6MjA4MTg4NjY4Mn0.zeaOCT_ffMAMn-Ex-lwTA9Qe5rH0v4qVN2oEIAj5-9Y"